server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: xl-api-interface
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
  redis:
    host: 110.41.132.124
    port: 7529
    database: 0
    password: 12345678
#    host: localhost
#    port: 6379
#    database: 0
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    qosEnable: false
    enable-file-cache: false
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
#    address: nacos://172.17.0.3:8848
#    address: nacos://127.0.0.1:8848
#    address: nacos://110.41.132.124:8848
    address: nacos://18.162.214.254:8848