server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: qi-api-interface
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: dubbo-springboot-demo-provider
    enable-file-cache: false
    qos-enable: true
    qos-port: 33333
    qos-accept-foreign-ip: false
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848