server:
  port: 8081
  servlet:
    context-path: /api
spring:
  profiles:
    active: dev
  mvc:
    path match:
      matching-strategy: ant_path_matcher
qi:
  api:
    client:
      access-key: 7052a8594339a519e0ba5eb04a267a60
      secret-key: d8d6df60ab209385a09ac796f1dfe3e1

